### PR TITLE
Fix konk fails install on ubuntu

### PR DESCRIPTION
**Pull request by schattmicro**
Updated README.md 
1. Add logged in non-root user on Ubuntu to docker group
2. Refresh docker group membership of logged in non-root user

### CODE REVIEW

**Comment by csantanapr** [comment]
There are 2 issues I see:

- There are problems with the markdown rendering of this PR. Please preview in github.com or locally https://github.com/csantanapr/knative-kind/blob/b65c9a2098398bb2edac217f08b9075594d6d83c/README.md
- Could you signoff the PR to make the DCO bot happy?

**Review by csantanapr — CHANGES_REQUESTED** [review]
problems with rendering the site

**Comment by schattmicro** [comment]
Do I need to create a new PR with developer sign off added to commit messages?

**Comment by schattmicro** [comment]
> problems with rendering the site
Can you please let me know which markdown editor to use to make sure we dont run into rendering issues you reported?

**Comment by csantanapr** [comment]
I use Visual Studio Code, it has a button on the top right to preview the markdown.

For signoff if your not familiar to rebase, squash, and force push to re-use this PR, you can close the PR and do it in a new branch out of master.

**Comment by schattmicro** [comment]
Incorporated the review comments

**Comment by csantanapr** [comment]
The PR #33 overrides this one

**Pull request closed without merging**
