### PR TITLE
king of the hill

### PR DESCRIPTION
**Pull request by csantanapr**
- expose broker using kourier Kingress
- kingress must be in same namespace as service

### CODE REVIEW

**Comment by csantanapr** [comment]
@salaboy here is the update to make broker external accesible

**Comment by salaboy** [comment]
@csantanapr awesome! I should do the same for contour, right? Just another ingress definition with the right annotations..

**Comment by csantanapr** [comment]
oh yes I forgot about contour

**Comment by csantanapr** [comment]
Can you make a PR to update to readme and scripts, 
I tried to create the Kingress yaml without an annotation class and didn't work.

You PR should:
- get the current configure networking class and put in a variable, one liner kubectl
- use the variable to put the variable value in the Kingress yaml

**Pull request merged**
